name: Compile Windows Exe

on:
  push:
    branches: [ master ]

jobs:

  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    container: marker5a/mxe:latest
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
    
      - name: Get that code
        uses: actions/checkout@v3
        
      - name: Compile the code and strip it out
        run: |
          cmake .
          make -j32
          strip EasyTerm.exe
          mkdir downloads
          mv EasyTerm.exe downloads
    
      - name: Upload to artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
