name: Compile Windows Exe

on:
  push:

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    container: marker5a/mxe:latest
    steps:
    
      - name: Get that code
        uses: actions/checkout@v3
        
      - name: Compile the code and strip it out
        run: |
          cmake .
          make -j32
          strip EasyTerm.exe
          mkdir downloads
          mv EasyTerm.exe downloads
    
      - name: Upload to artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
