name: Compile Windows Exe

on:
  push:

jobs:

  build:
    name: Build in MXE Docker
    runs-on: ubuntu-latest
    container: marker5a/mxe:latest
    steps:
      - name: Get that code
        uses: actions/checkout@v3
        
      - name: Compile the code and strip it out
        run: |
          cmake .
          make -j32
          strip EasyTerm.exe
          mkdir -p downloads
          mv EasyTerm.exe downloads/

      - name: Upload build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: easyterm-exe
          path: downloads

  upload:
    name: Upload Artifact to GitHub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: easyterm-exe
          path: build_artifacts

      - name: Re-upload for GitHub Downloads (or use as needed)
        uses: actions/upload-artifact@v4
        with:
          name: assets-for-download
          path: build_artifacts
