name: Build Debian Package

on:
  push:
    branches:
      - test_packaging  # Change this to your main branch name

jobs:
  build-debian-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Build Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential debhelper libqt5serialport5 libqt5serialport5-dev qtbase5-dev qt5-qmake cmake

    - name: Build C++ Project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Copy Debian Directory to Build Directory
      run: cp -r packaging/debian ./build/

    - name: Create Debian Package
      run: |
        cd build
        dpkg-buildpackage -us -uc
        cd ..

    - name: Upload Debian Package
      uses: actions/upload-artifact@v2
      with:
        name: deb-package
        path: ./*.deb
